//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCenterApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleServiciosMantenimientos
    {
        public int idDetalleServiciosMantenimientos { get; set; }
        public int idServicio { get; set; }
        public int idMantenimiento { get; set; }
        public double ValorServicio { get; set; }
    
        public virtual Mantenimientos Mantenimientos { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
