//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCenterApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRepuestosMantenimientos
    {
        public int idDetalleRepuestosMantenimientos { get; set; }
        public int idMantenimiento { get; set; }
        public int idRepuesto { get; set; }
        public int CantidadRepuestos { get; set; }
        public double PrecioUnidad { get; set; }
    
        public virtual Mantenimientos Mantenimientos { get; set; }
        public virtual Repuestos Repuestos { get; set; }
    }
}
