//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCenterApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
        }
    
        public int idFactura { get; set; }
        public int idCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> ValorBruto { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> ValorTotal { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
    }
}
