//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCenterApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mantenimientos()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
            this.DetalleRepuestosMantenimientos = new HashSet<DetalleRepuestosMantenimientos>();
            this.DetalleServiciosMantenimientos = new HashSet<DetalleServiciosMantenimientos>();
        }
    
        public int idMantenimiento { get; set; }
        public int idMecanico { get; set; }
        public string placa { get; set; }
        public string EstadoMantenimiento { get; set; }
        public System.DateTime FechaMantenimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRepuestosMantenimientos> DetalleRepuestosMantenimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleServiciosMantenimientos> DetalleServiciosMantenimientos { get; set; }
        public virtual Mecanicos Mecanicos { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
